#
###################################
# Site wide configuration
####################################
#
title: Le Blog du Bêta-Lab
email: betalab@labetapi.fr
description: A simple and awesome blog theme powered by jekyll.
url: https://beta-lab.github.io/leonids/ # the base hostname & protocol for your site


#
###################################
# Jekyll configuration
####################################
#
timezone:          Europe/Paris
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Betablog
  avatar: leonids-logo.png
  job: "A jekyll theme"
  bio: "A simple and awesome blog theme powered by jekyll."
  email: betalab@labetapi.fr
  twitter: #username
  facebook: #username
  github: #username
