#
###################################
# Site wide configuration
####################################
#
title: Le Blog du Bêta-Lab
email: betalab@labetapi.fr
description:
url: https://beta-lab.github.io/ # the base hostname & protocol for your site


#
###################################
# Jekyll configuration
####################################
#
timezone:          Europe/Paris
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Betablog
  avatar: betalab.png
  job: "Le blog du Bêta-Lab"
  bio: <a href="http://labetapi.fr/">Le Bêta-Lab - FabLab de la Bêta-Pi</a>
  email: betalab@labetapi.fr
  twitter: labetapi
  facebook: LaBetaPI

prose:
  rooturl: '_posts'
  siteurl: 'http://beta-lab.github.io'
  relativeLinks: 'http://prose.github.io/starter/links.jsonp'
  media: 'img'
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "published"
        field:
          element: "hidden"
          value: "true"
      - name: "comments"
        field:
          element: "hidden"
          value: "hidden"
      - name: "categories"
        field:
          element: "text"
          label: "Catégorie(s)"
      - name: "title"
        field:
          element: "text"
label: "title"
